version: '3'

services:
  app-front:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
    command: sh -c "npx serve dist -l 8000"
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /etc/letsencrypt/nginx.config:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    restart: always
    networks:
      - app-network

networks:
  app-network:
